services:
  ami.eduwork:
    image: ${DOCKER_REGISTRY-}amieduwork
    build:
      context: .
      dockerfile: AMI.EduWork/Dockerfile
    depends_on:
       - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

volumes:
  sqlserver-data:
