services:
  ami.eduwork:
    image: amieduwork:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AMI.EduWork"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages
    volumes:
      - C:\FactoryXproject\factory-x-summer-internship-2025\AMI.EduWork\AMI.EduWork:/app:rw
      - C:\FactoryXproject\factory-x-summer-internship-2025\AMI.EduWork:/src:rw
      - C:\Users\Adrian\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Adrian\.nuget\packages:/.nuget/packages:ro
      - D:\Apps\Visual studio 2022\components\NuGetPackages:/.nuget/fallbackpackages:ro
      - C:\Users\Adrian\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\Adrian\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\Adrian\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\Adrian\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - D:\Apps\Visual studio 2022\ide\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net6.0:/VSTools:ro
      - D:\Apps\Visual studio 2022\ide\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages  \"/app/bin/Debug/net9.0/AMI.EduWork.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true